# configuration dictionary
app_name: DiscordGPT
id: 1234567890
display_name: GPT GlamBot
key_trigger: !
color: "#FF69B4"  # Hot pink
model: gpt-3.5-turbo
context: 1024
intents:
  - "tell me a joke"
  - "give me some advice"
discord_token: "your_discord_token_here"
openai_key: "your_openai_key_here"
candc: 5